name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:

  build:
    container:
      image: racket/racket-ci:latest
      options: --init

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        export PATH=$PATH:`pwd`/racket/bin
        raco test -l

    - name: site - make
      run: racket main.rkt

    - name: site - deploy
      uses: jsmrcaga/action-netlify-deploy@v1.1.0
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_TO_PROD: true
        build_directory: tmp
