name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:

  build:
    container:
      image: racket/racket-ci:latest
      options: --init

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        export PATH=$PATH:`pwd`/racket/bin
        raco test -l
        racket main.rkt
