name: Site

on:
  push:
    branches: 'main'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Racket
      uses: Bogdanp/setup-racket@v0.11
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '7.9'
    - name: Install Package and its Dependencies
      run: raco pkg install --auto --batch

    - name: site - make
      run: racket main.rkt

    - name: site - deploy
      uses: jsmrcaga/action-netlify-deploy@v1.1.0
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_TO_PROD: true
        build_directory: tmp
